
services:
  api:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.api
      context: ./
    container_name: api
    command: ["wait-for-it", "-t", "60", "mysql:3306", "--", "bash", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 1"]
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - mysql
    # environment:
    #   - ENVIRONMENT=dev
    #   - TESTING=0

  mysql:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.db
      context: ./
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=caching_sha2_password
    restart: on-failure:3
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}